import { DoctorUser, PatientUser, Appointment, MedicalRecord } from '../types.ts';

export const INITIAL_DOCTORS: DoctorUser[] = [
  {
    id: 'doc-1',
    email: 'dr.alex@carepulse.com',
    name: 'Dr. Alex Vance',
    role: 'doctor',
    department: 'Cardiology',
    specialty: 'Interventional Cardiologist',
    qualification: 'MD, DM (Cardiology), FACC',
    experienceYears: 16,
    uniqueCases: 'Performed 120+ successful transcatheter aortic valve replacements (TAVR) and complex left main coronary angioplasties.',
    consultationFee: 120,
    rating: 4.9,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
    bio: 'Senior consultant cardiologist specializing in heart failure management, coronary artery disease, and minimally invasive cardiac procedures.',
    roomNo: 'Suite 302, Heart Wing',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-2',
    email: 'dr.elena@carepulse.com',
    name: 'Dr. Elena Rostova',
    role: 'doctor',
    department: 'Neurology',
    specialty: 'Neurophysiologist & Stroke Specialist',
    qualification: 'MD, DNB (Neurology), Fellowship in Epilepsy',
    experienceYears: 14,
    uniqueCases: 'Spearheaded deep brain stimulation therapy for 65+ Parkinson patients; specialized in refractory migraine & complex neuropathy management.',
    consultationFee: 140,
    rating: 4.95,
    availableDays: ['Monday', 'Wednesday', 'Thursday', 'Saturday'],
    availableSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:00 PM'],
    bio: 'Expert neurologist dedicated to acute stroke care, chronic headache disorders, multiple sclerosis, and advanced neuro-diagnostics.',
    roomNo: 'Suite 410, Neuro Science Block',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-78a0d4c14777?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-3',
    email: 'dr.marcus@carepulse.com',
    name: 'Dr. Marcus Thorne',
    role: 'doctor',
    department: 'Orthopedics',
    specialty: 'Joint Replacement & Trauma Surgeon',
    qualification: 'MS (Orthopedics), MCh (Orth Surgery, UK)',
    experienceYears: 18,
    uniqueCases: 'Pioneered custom 3D-printed titanium pelvic reconstruction implants for severe vehicular trauma survivors.',
    consultationFee: 110,
    rating: 4.85,
    availableDays: ['Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    availableSlots: ['10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM'],
    bio: 'Renowned orthopedic surgeon specializing in robotic total knee & hip replacements, sports injuries, and complex fracture revisions.',
    roomNo: 'Suite 205, Ortho Center',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-4',
    email: 'dr.maya@carepulse.com',
    name: 'Dr. Maya Lin',
    role: 'doctor',
    department: 'Pediatrics',
    specialty: 'Pediatric Pulmonologist & Intensivist',
    qualification: 'MD (Pediatrics), Fellowship in Pediatric Critical Care',
    experienceYears: 12,
    uniqueCases: 'Managed critical respiratory distress cases in pediatric ICU with 98% recovery rate; specialized in pediatric asthma & allergy immunotherapy.',
    consultationFee: 95,
    rating: 4.92,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
    availableSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM'],
    bio: 'Compassionate pediatrician focusing on newborn growth monitoring, childhood allergies, viral illnesses, and adolescent wellness.',
    roomNo: 'Suite 108, Child Care Pavilion',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-5',
    email: 'dr.samuel@carepulse.com',
    name: 'Dr. Samuel Harper',
    role: 'doctor',
    department: 'Dermatology',
    specialty: 'Cosmetic & Clinical Dermatologist',
    qualification: 'MD (Dermatology, Venereology & Leprosy)',
    experienceYears: 11,
    uniqueCases: 'Developed personalized biological therapy regimens for severe recalcitrant psoriasis and chronic autoimmune skin conditions.',
    consultationFee: 100,
    rating: 4.88,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '04:00 PM'],
    bio: 'Specialist in laser treatments, skin cancer screenings, severe acne care, eczema management, and aesthetic dermatology.',
    roomNo: 'Suite 112, Skin Clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-6',
    email: 'dr.priya@carepulse.com',
    name: 'Dr. Priya Sharma',
    role: 'doctor',
    department: 'General Medicine',
    specialty: 'Internal Medicine & Diabetologist',
    qualification: 'MBBS, MD (General Medicine), FACP',
    experienceYears: 15,
    uniqueCases: 'Successfully treated multi-organ fever cases, acute septic shock, and complex metabolic syndrome reversals.',
    consultationFee: 85,
    rating: 4.9,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
    bio: 'Primary care lead treating hypertension, type 2 diabetes, infectious fevers, thyroid disorders, and routine preventive health checkups.',
    roomNo: 'Suite 101, Outpatient Clinic',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-78a0d4c14777?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-7',
    email: 'dr.kevin@carepulse.com',
    name: 'Dr. Kevin O\'Connor',
    role: 'doctor',
    department: 'ENT',
    specialty: 'Otorhinolaryngologist & Sinus Surgeon',
    qualification: 'MS (ENT), DLO',
    experienceYears: 13,
    uniqueCases: 'Performed 200+ endoscopic sinus surgeries, micro-ear tympanoplasties, and vertigo rehabilitation programs.',
    consultationFee: 105,
    rating: 4.87,
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM'],
    bio: 'Expert in hearing loss diagnostics, sinus blockage, tonsillitis, voice disorders, and balance disorders.',
    roomNo: 'Suite 218, ENT Center',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'doc-8',
    email: 'dr.arun@carepulse.com',
    name: 'Dr. Arun Patel',
    role: 'doctor',
    department: 'Gastroenterology',
    specialty: 'Hepatologist & Endoscopist',
    qualification: 'MD, DM (Gastroenterology)',
    experienceYears: 17,
    uniqueCases: 'Managed complex acute pancreatitis recoveries and therapeutic ERCP gallstone extractions.',
    consultationFee: 130,
    rating: 4.91,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableSlots: ['09:30 AM', '11:30 AM', '02:30 PM', '04:30 PM'],
    bio: 'Focuses on acid reflux, inflammatory bowel disease (IBD), fatty liver disease, and advanced endoscopic procedures.',
    roomNo: 'Suite 315, Digestive Health Block',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_PATIENTS: PatientUser[] = [
  {
    id: 'pat-1',
    email: 'sarah.connor@example.com',
    name: 'Sarah Connor',
    role: 'patient',
    age: 34,
    gender: 'Female',
    phone: '+1 (555) 234-5678',
    bloodGroup: 'A+',
    allergies: ['Penicillin', 'Dust Mites'],
  },
  {
    id: 'pat-2',
    email: 'john.doe@example.com',
    name: 'John Doe',
    role: 'patient',
    age: 48,
    gender: 'Male',
    phone: '+1 (555) 876-5432',
    bloodGroup: 'O+',
    allergies: ['Sulfa drugs'],
  },
  {
    id: 'pat-3',
    email: 'emily.watson@example.com',
    name: 'Emily Watson',
    role: 'patient',
    age: 27,
    gender: 'Female',
    phone: '+1 (555) 456-7890',
    bloodGroup: 'B+',
    allergies: ['None'],
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'pat-1',
    patientName: 'Sarah Connor',
    patientAge: 34,
    patientGender: 'Female',
    patientEmail: 'sarah.connor@example.com',
    doctorId: 'doc-2',
    doctorName: 'Dr. Elena Rostova',
    doctorSpecialty: 'Neurophysiologist & Stroke Specialist',
    doctorDepartment: 'Neurology',
    appointmentDate: '2026-08-05',
    timeSlot: '10:30 AM',
    symptoms: 'Recurring right-sided throbbing headache, light sensitivity, and mild dizziness for 3 days.',
    severity: 'Moderate',
    aiMatchReasoning: 'Matched with Neurology based on unilateral pulsating cranial pain accompanied by photophobia.',
    status: 'scheduled',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'apt-102',
    patientId: 'pat-2',
    patientName: 'John Doe',
    patientAge: 48,
    patientGender: 'Male',
    patientEmail: 'john.doe@example.com',
    doctorId: 'doc-1',
    doctorName: 'Dr. Alex Vance',
    doctorSpecialty: 'Interventional Cardiologist',
    doctorDepartment: 'Cardiology',
    appointmentDate: '2026-07-20',
    timeSlot: '02:00 PM',
    symptoms: 'Exertional chest tightness, shortness of breath upon climbing stairs.',
    severity: 'High',
    aiMatchReasoning: 'Cardiology specialist assigned due to exertional dyspnea and retrosternal chest pressure.',
    status: 'completed',
    createdAt: '2026-07-18T14:30:00Z',
  },
  {
    id: 'apt-103',
    patientId: 'pat-1',
    patientName: 'Sarah Connor',
    patientAge: 34,
    patientGender: 'Female',
    patientEmail: 'sarah.connor@example.com',
    doctorId: 'doc-6',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialty: 'Internal Medicine & Diabetologist',
    doctorDepartment: 'General Medicine',
    appointmentDate: '2026-06-15',
    timeSlot: '09:00 AM',
    symptoms: 'Routine wellness checkup and mild seasonal allergy symptoms.',
    severity: 'Low',
    status: 'completed',
    createdAt: '2026-06-10T09:15:00Z',
  }
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'med-201',
    patientId: 'pat-2',
    patientName: 'John Doe',
    doctorId: 'doc-1',
    doctorName: 'Dr. Alex Vance',
    doctorSpecialty: 'Interventional Cardiologist',
    appointmentId: 'apt-102',
    visitDate: '2026-07-20',
    diagnosis: 'Mild Essential Hypertension & Mild Stable Angina',
    symptomsSummary: 'Exertional chest tightness, fatigue, blood pressure recorded at 145/92 mmHg.',
    prescriptions: [
      {
        id: 'rx-1',
        medicineName: 'Amlodipine Besylate',
        dosage: '5 mg',
        frequency: 'Once daily in the morning',
        duration: '30 Days',
        instructions: 'Take after breakfast with water.',
      },
      {
        id: 'rx-2',
        medicineName: 'Atorvastatin',
        dosage: '10 mg',
        frequency: 'Once daily at bedtime',
        duration: '30 Days',
        instructions: 'Helps control lipid levels.',
      }
    ],
    clinicalNotes: 'ECG showed normal sinus rhythm with mild non-specific T wave changes. Recommended low-sodium diet, 30 minutes light walking daily, and lipid panel blood test before follow-up.',
    followUpDate: '2026-08-20',
    vitals: {
      bp: '145/92 mmHg',
      pulse: '78 bpm',
      temp: '98.4 °F',
      weight: '82 kg',
    },
    createdAt: '2026-07-20T15:00:00Z',
  },
  {
    id: 'med-202',
    patientId: 'pat-1',
    patientName: 'Sarah Connor',
    doctorId: 'doc-6',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialty: 'Internal Medicine & Diabetologist',
    appointmentId: 'apt-103',
    visitDate: '2026-06-15',
    diagnosis: 'Acute Seasonal Allergic Rhinitis',
    symptomsSummary: 'Nasal congestion, sneezing, mild watery eyes during seasonal change.',
    prescriptions: [
      {
        id: 'rx-3',
        medicineName: 'Levocetirizine',
        dosage: '5 mg',
        frequency: 'Once daily at night',
        duration: '7 Days',
        instructions: 'Avoid driving if drowsy.',
      },
      {
        id: 'rx-4',
        medicineName: 'Fluticasone Nasal Spray',
        dosage: '50 mcg/actuation',
        frequency: '2 sprays in each nostril daily',
        duration: '10 Days',
        instructions: 'Blow nose gently before administering.',
      }
    ],
    clinicalNotes: 'Chest lungs clear to auscultation. Throat normal. Patient advised to stay hydrated and avoid dusty environments.',
    vitals: {
      bp: '118/76 mmHg',
      pulse: '72 bpm',
      temp: '98.6 °F',
      weight: '62 kg',
    },
    createdAt: '2026-06-15T10:00:00Z',
  }
];
